---
- include_vars: setenv.yml

- name: Create the directory for git repo
  file:
      path=/tmp/mygitrepo/ owner={{juser}} group={{jgroup}} mode=0777 state=directory

#Download configs from git repo
- name: Download jenkins config git repo
  become: yes
  become_user: balaram
  git: 
     repo=git@github.com:re86/jenkinsrepo.git
     dest=/tmp/mygitrepo/
     update=yes
     accept_hostkey=yes

#Move job configs to jenkins
- raw: cp -R /tmp/mygitrepo/jobs/* /usr/share/tomcat7/.jenkins/jobs/
- raw: chown -R {{juser}}:{{jgroup}} /usr/share/tomcat7/.jenkins/jobs/*

#Restart Tomcat
- name: Start tomcat to create directory structure
  sudo: yes
  service: name=tomcat7 state=restarted

#Install curl 
- name: install curl
  sudo: yes
  command: "apt-get -y install curl"

- name: Wait untils Jenkins web API is available
  shell: curl --head --silent http://localhost:8080/jenkins/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: 12
  delay: 5

#Create views for the master
- name: testing module2
  command: 'curl -vvv -X POST -d @/tmp/mygitrepo/views/{{item.name}} -H "Content-Type: text/xml" http://localhost:8080/jenkins/createView?name={{item.version}}'
  with_items:
   - { name: 'admin_tab.xml', version: 'Admin-Tools' }
   - { name: 'cidev_tab.xml', version: 'CI-DEV' }
   - { name: 'cimas_tab.xml', version: 'CI-MAS' }
   - { name: 'cirel_tab.xml', version: 'CI-REL' }
   - { name: 'cicube_tab.xml', version: 'CCube' }
   - { name: 'cidevbuildstatus_tab.xml', version: 'CI%20-%20DEV%20-%20Build%20Status' }
   - { name: 'mobilebuildpipeline_tab.xml', version: 'Mobile-Build-Pipeline' }
   - { name: 'mydashboard_tab.xml', version: 'My%20Dashboard' }
   - { name: 'nightlybuilds_tab.xml', version: 'Nightly-Builds' }
   - { name: 'ondemandbuilds_tab.xml', version: 'OnDemand-Builds' }
   - { name: 'regressionjobs_tab.xml', version: 'Regression%20Jobs' }
   - { name: 'regressionjobstatus_tab.xml', version: 'Regression%20Jobs%20Status' }
   - { name: 'sanityjobs_tab.xml', version: 'Sanity%20Jobs' }
   - { name: 'sanityjobstatus_tab.xml', version: 'Sanity%20Jobs%20Status' }
   - { name: 'donotuse_tab.xml', version: 'DONOT%20USE' }