---
- include_vars: setenv.yml

#Download jenkins plugins
- name: Create plugin directory
  file:
      path=/tmp/jplugins mode=0777 state=directory

- action: get_url url=https://updates.jenkins-ci.org/download/plugins/{{item.name}}/{{item.version}}/{{item.name}}.hpi dest=/tmp/jplugins mode=0777
  with_items:
   - { name: 'build-monitor-plugin', version: '1.6+build.132' }
   - { name: 'git', version: '2.3.1' }
   - { name: 'windows-slaves', version: '1.0' }
   - { name: 'ant', version: '1.2' }
   - { name: 'build-timeout', version: '1.14' }
   - { name: 'conditional-buildstep', version: '1.3.3' }
   - { name: 'config-autorefresh-plugin', version: '1.0' }
   - { name: 'copyartifact', version: '1.31' }
   - { name: 'credentials', version: '1.16.1' }
   - { name: 'cucumber', version: '0.0.2' }
   - { name: 'cucumber-reports', version: '0.0.23' }
   - { name: 'cucumber-testresult-plugin', version: '0.5.2' }
   - { name: 'cucumber-perf', version: '2.0.6' }
   - { name: 'cvs', version: '2.11' }
   - { name: 'dashboard-view', version: '2.9.4' }
   - { name: 'delivery-pipeline-plugin', version: '0.8.6' }
   - { name: 'description-setter', version: '1.9' }
   - { name: 'doxygen', version: '0.16' }
   - { name: 'ease-plugin', version: '1.2.3' }
   - { name: 'email-ext', version: '2.38.1' }
   - { name: 'envinject', version: '1.89' }
   - { name: 'extra-columns', version: '1.14' }
   - { name: 'git-client', version: '1.10.1' }
   - { name: 'global-variable-string-parameter', version: '1.2' }
   - { name: 'hockeyapp', version: '1.1.0' }
   - { name: 'htmlpublisher', version: '1.3' }
   - { name: 'javadoc', version: '1.1' }
   - { name: 'jquery', version: '1.7.2-1' }
   - { name: 'jquery-ui', version: '1.0.2' }
   - { name: 'ldap', version: '1.6' }
   - { name: 'mailer', version: '1.10' }
   - { name: 'junit', version: '1.0' }
   - { name: 'mask-passwords', version: '2.7.2' }
   - { name: 'matrix-auth', version: '1.1' }
   - { name: 'matrix-project', version: '1.3' }
   - { name: 'maven-plugin', version: '2.5' }
   - { name: 'monitoring', version: '1.52.1' }
   - { name: 'pam-auth', version: '1.1' }
   - { name: 'parameterized-trigger', version: '2.25' }
   - { name: 'progress-bar-column-plugin', version: '1.0' }
   - { name: 'publish-over-ssh', version: '1.11' }
   - { name: 'role-strategy', version: '2.2.0' }
   - { name: 'ruby-runtime', version: '0.12' }
   - { name: 'run-condition', version: '1.0' }
   - { name: 'rvm', version: '0.4' }
   - { name: 'scm-api', version: '0.2' }
   - { name: 'scm-sync-configuration', version: '0.0.8' }
   - { name: 'shelve-project-plugin', version: '1.5' }
   - { name: 'simple-theme-plugin', version: '0.3' }
   - { name: 'ssh-credentials', version: '1.9' }
   - { name: 'ssh-slaves', version: '1.5' }
   - { name: 'subversion', version: '1.54' }
   - { name: 'tfs', version: '3.1.1' }
   - { name: 'thinBackup', version: '1.7.4' }
   - { name: 'token-macro', version: '1.10' }
   - { name: 'translation', version: '1.10' }
   - { name: 'ws-cleanup', version: '0.22' }
   - { name: 'build-pipeline-plugin', version: '1.4.3' }


#Move plugins configs to jenkins
- raw: mv /tmp/jplugins/* /usr/share/tomcat7/.jenkins/plugins/
- raw: chown -R {{juser}}:{{jgroup}} /usr/share/tomcat7/.jenkins/jobs

- name: ensure tomcat is restarted
  sudo: yes
  service: name=tomcat7 state=restarted