---
- name: update debian packages
  apt: update_cache=true

- name: install NGinx
  apt: name=nginx state=present

#- name: copy nginx.conf to the server
#  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx